CREATE TABLE IF NOT EXISTS "seo_site_config" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "site_name" varchar(128) NOT NULL,
  "site_url" varchar(512) NOT NULL,
  "default_title_suffix" varchar(128) NOT NULL DEFAULT '',
  "default_description" varchar(500) NOT NULL DEFAULT '',
  "default_robots" varchar(64) NOT NULL DEFAULT 'index,follow',
  "default_og_image" varchar(1024) NOT NULL DEFAULT '',
  "default_locale" varchar(32) NOT NULL DEFAULT 'zh-CN',
  "navigation_template" varchar(32) NOT NULL DEFAULT 'VANZ_B2B',
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_tenant_site_active" ON "seo_site_config"
    ("tenant_id", "site_id", "active_record");

CREATE TABLE IF NOT EXISTS "seo_metadata" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "entity_type" varchar(32) NOT NULL,
  "entity_id" bigint NOT NULL,
  "locale" varchar(32) NOT NULL DEFAULT 'zh-CN',
  "seo_title" varchar(255) NOT NULL DEFAULT '',
  "meta_description" varchar(500) NOT NULL DEFAULT '',
  "focus_keyphrase" varchar(255) NOT NULL DEFAULT '',
  "related_keyphrases" varchar(4000),
  "canonical_url" varchar(1024) NOT NULL DEFAULT '',
  "robots_index" boolean NOT NULL DEFAULT TRUE,
  "robots_follow" boolean NOT NULL DEFAULT TRUE,
  "og_title" varchar(255) NOT NULL DEFAULT '',
  "og_description" varchar(500) NOT NULL DEFAULT '',
  "og_image" varchar(1024) NOT NULL DEFAULT '',
  "schema_type" varchar(64) NOT NULL DEFAULT '',
  "publish_status" varchar(16) NOT NULL DEFAULT 'DRAFT',
  "version" int NOT NULL DEFAULT 1,
  "published_time" timestamp,
  "latest_analysis_id" bigint,
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_entity_locale_active" ON "seo_metadata"
    ("tenant_id", "site_id", "entity_type", "entity_id", "locale", "active_record");

CREATE INDEX IF NOT EXISTS "idx_public_resolve" ON "seo_metadata"
    ("tenant_id", "site_id", "entity_type", "entity_id", "locale", "publish_status");

CREATE INDEX IF NOT EXISTS "idx_latest_analysis" ON "seo_metadata"
    ("tenant_id", "latest_analysis_id");

CREATE TABLE IF NOT EXISTS "seo_analysis" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "source_type" varchar(16) NOT NULL,
  "source_id" bigint,
  "entity_type" varchar(32) NOT NULL,
  "entity_id" bigint,
  "locale" varchar(32) NOT NULL DEFAULT 'zh-CN',
  "focus_keyphrase" varchar(255) NOT NULL,
  "input_snapshot" varchar(20000) NOT NULL,
  "content_hash" char(64) NOT NULL,
  "idempotency_key" varchar(128) NOT NULL,
  "previous_analysis_id" bigint,
  "overall_relevance_percent" int,
  "confidence_percent" int,
  "total_score" int,
  "engine_version" varchar(64) NOT NULL,
  "rule_profile_version" varchar(64) NOT NULL,
  "dictionary_version" varchar(64) NOT NULL,
  "semantic_model_version" varchar(128),
  "analysis_status" varchar(16) NOT NULL DEFAULT 'PENDING',
  "failure_code" varchar(64),
  "failure_message" varchar(500),
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_analysis_idempotency_active" ON "seo_analysis"
    ("tenant_id", "idempotency_key", "active_record");
CREATE INDEX IF NOT EXISTS "idx_analysis_entity_history" ON "seo_analysis"
    ("tenant_id", "site_id", "entity_type", "entity_id", "locale", "create_time");

CREATE TABLE IF NOT EXISTS "seo_analysis_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "analysis_id" bigint NOT NULL,
  "rule_code" varchar(96) NOT NULL,
  "category" varchar(32) NOT NULL,
  "status" varchar(24) NOT NULL,
  "score" decimal(8,4),
  "max_score" decimal(8,4),
  "evidence" varchar(4000),
  "message" varchar(1000) NOT NULL DEFAULT '',
  "recommendation" varchar(1000) NOT NULL DEFAULT '',
  "sort" int NOT NULL DEFAULT 0,
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_analysis_rule" ON "seo_analysis_item"
    ("tenant_id", "analysis_id", "rule_code");

CREATE TABLE IF NOT EXISTS "seo_keyword_analysis" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "analysis_id" bigint NOT NULL,
  "keyword_type" varchar(16) NOT NULL,
  "keyword" varchar(255) NOT NULL,
  "normalized_keyword" varchar(255) NOT NULL,
  "sort" int NOT NULL,
  "key_position_percent" int,
  "lexical_match_percent" int,
  "semantic_percent" int,
  "distribution_percent" int,
  "intent_coverage_percent" int,
  "relevance_percent" int,
  "confidence_percent" int NOT NULL DEFAULT 0,
  "grade" varchar(16),
  "analysis_status" varchar(16) NOT NULL,
  "exact_match_count" int NOT NULL DEFAULT 0,
  "variant_match_count" int NOT NULL DEFAULT 0,
  "matched_locations" varchar(4000),
  "dictionary_version" varchar(64) NOT NULL,
  "semantic_model_version" varchar(128),
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_keyword_order_active" ON "seo_keyword_analysis"
    ("tenant_id", "analysis_id", "keyword_type", "sort", "active_record");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_keyword_normalized_active" ON "seo_keyword_analysis"
    ("tenant_id", "analysis_id", "normalized_keyword", "active_record");
CREATE INDEX IF NOT EXISTS "idx_keyword_analysis" ON "seo_keyword_analysis"
    ("tenant_id", "analysis_id", "sort");

CREATE TABLE IF NOT EXISTS "seo_keyword_analysis_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "keyword_analysis_id" bigint NOT NULL,
  "rule_code" varchar(96) NOT NULL,
  "dimension" varchar(24) NOT NULL,
  "severity" varchar(16) NOT NULL,
  "status" varchar(24) NOT NULL,
  "score" decimal(8,4),
  "max_score" decimal(8,4),
  "content_location" varchar(64),
  "evidence" varchar(4000),
  "reason" varchar(1000) NOT NULL DEFAULT '',
  "recommendation" varchar(1000) NOT NULL DEFAULT '',
  "recoverable_score" decimal(8,4),
  "sort" int NOT NULL DEFAULT 0,
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_keyword_rule" ON "seo_keyword_analysis_item"
    ("tenant_id", "keyword_analysis_id", "rule_code");
CREATE INDEX IF NOT EXISTS "idx_keyword_item_sort" ON "seo_keyword_analysis_item"
    ("tenant_id", "keyword_analysis_id", "sort");

CREATE TABLE IF NOT EXISTS "website_navigation_revision" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "locale" varchar(32) NOT NULL DEFAULT 'en',
  "revision_no" int NOT NULL,
  "status" varchar(16) NOT NULL DEFAULT 'DRAFT',
  "version" int NOT NULL DEFAULT 1,
  "published_time" timestamp,
  "published_by" varchar(64) NOT NULL DEFAULT '',
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_navigation_revision_no" ON "website_navigation_revision"
    ("tenant_id", "site_id", "locale", "revision_no");
CREATE INDEX IF NOT EXISTS "idx_navigation_public" ON "website_navigation_revision"
    ("tenant_id", "site_id", "locale", "status");

CREATE TABLE IF NOT EXISTS "website_navigation_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "revision_id" bigint NOT NULL,
  "item_key" varchar(96) NOT NULL,
  "parent_item_key" varchar(96) NOT NULL DEFAULT '',
  "item_type" varchar(16) NOT NULL,
  "label" varchar(64) NOT NULL,
  "page_key" varchar(32),
  "target_key" varchar(64),
  "category_id" bigint,
  "sort" int NOT NULL DEFAULT 0,
  "visible" boolean NOT NULL DEFAULT TRUE,
  "open_mode" varchar(16) NOT NULL DEFAULT '_self',
  "style_variant" varchar(32) NOT NULL DEFAULT 'DEFAULT',
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_navigation_item_active" ON "website_navigation_item"
    ("tenant_id", "revision_id", "item_key", "active_record");
CREATE INDEX IF NOT EXISTS "idx_navigation_item_order" ON "website_navigation_item"
    ("tenant_id", "revision_id", "sort", "id");
