CREATE TABLE IF NOT EXISTS "seo_site_config" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "site_name" varchar(128) NOT NULL,
  "site_url" varchar(512) NOT NULL,
  "default_title_suffix" varchar(128) NOT NULL DEFAULT '',
  "default_description" varchar(500) NOT NULL DEFAULT '',
  "default_robots" varchar(64) NOT NULL DEFAULT 'index,follow',
  "default_og_image" varchar(1024) NOT NULL DEFAULT '',
  "default_locale" varchar(32) NOT NULL DEFAULT 'zh-CN',
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_tenant_site_active" ON "seo_site_config"
    ("tenant_id", "site_id", "active_record");

CREATE TABLE IF NOT EXISTS "seo_metadata" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" bigint NOT NULL,
  "entity_type" varchar(32) NOT NULL,
  "entity_id" bigint NOT NULL,
  "locale" varchar(32) NOT NULL DEFAULT 'zh-CN',
  "seo_title" varchar(255) NOT NULL DEFAULT '',
  "meta_description" varchar(500) NOT NULL DEFAULT '',
  "focus_keyphrase" varchar(255) NOT NULL DEFAULT '',
  "related_keyphrases" varchar(4000),
  "canonical_url" varchar(1024) NOT NULL DEFAULT '',
  "robots_index" boolean NOT NULL DEFAULT TRUE,
  "robots_follow" boolean NOT NULL DEFAULT TRUE,
  "og_title" varchar(255) NOT NULL DEFAULT '',
  "og_description" varchar(500) NOT NULL DEFAULT '',
  "og_image" varchar(1024) NOT NULL DEFAULT '',
  "schema_type" varchar(64) NOT NULL DEFAULT '',
  "publish_status" varchar(16) NOT NULL DEFAULT 'DRAFT',
  "version" int NOT NULL DEFAULT 1,
  "published_time" timestamp,
  "creator" varchar(64) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) NOT NULL DEFAULT '',
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "active_record" tinyint GENERATED ALWAYS AS
      (CASE WHEN "deleted" = FALSE THEN 1 ELSE NULL END),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_entity_locale_active" ON "seo_metadata"
    ("tenant_id", "site_id", "entity_type", "entity_id", "locale", "active_record");

CREATE INDEX IF NOT EXISTS "idx_public_resolve" ON "seo_metadata"
    ("tenant_id", "site_id", "entity_type", "entity_id", "locale", "publish_status");
