-- H2 fixture for trade dashboard regression tests. Keep cost snapshot types aligned with MySQL.
CREATE TABLE IF NOT EXISTS "trade_order" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "no" varchar, "type" int, "terminal" int, "user_id" bigint,
  "user_ip" varchar, "user_remark" varchar, "address_verification" varchar,
  "status" int, "product_count" int, "pay_status" bit NOT NULL DEFAULT FALSE,
  "pay_time" timestamp, "finish_time" timestamp, "cancel_time" timestamp,
  "total_price" int, "order_price" int, "discount_price" int, "delivery_price" int,
  "adjust_price" int, "pay_price" int, "delivery_type" int,
  "refund_status" int, "refund_price" int, "after_sale_status" int,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "trade_order_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint, "order_id" bigint, "cart_id" bigint,
  "registry_id" bigint, "registry_item_id" bigint,
  "spu_id" bigint, "spu_name" varchar, "sku_id" bigint, "properties" varchar, "pic_url" varchar,
  "count" int, "comment_status" boolean, "price" int,
  "cost_price" bigint, "cost_estimated" bit DEFAULT FALSE,
  "discount_price" int, "delivery_price" int, "adjust_price" int, "pay_price" int,
  "coupon_price" int, "point_price" int, "use_point" int, "give_point" int, "vip_price" int,
  "after_sale_id" bigint, "after_sale_status" int,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "trade_after_sale" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "no" varchar,
  "status" int, "type" int, "way" int, "user_id" bigint,
  "order_id" bigint, "order_no" varchar, "order_item_id" bigint,
  "spu_id" bigint, "spu_name" varchar, "sku_id" bigint, "count" int,
  "refund_price" int, "refund_time" timestamp,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
