CREATE TABLE IF NOT EXISTS `member_gift_registry` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `public_code` varchar(64) NOT NULL,
  `registrant_name` varchar(128) NOT NULL,
  `co_registrant_name` varchar(128) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `event_type` varchar(64) DEFAULT NULL,
  `event_date` date DEFAULT NULL,
  `event_location` varchar(255) DEFAULT NULL,
  `visibility` varchar(32) NOT NULL DEFAULT 'public',
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `gift_card_preference` bit(1) NOT NULL DEFAULT b'0',
  `message_preference` bit(1) NOT NULL DEFAULT b'1',
  `before_event_address_line1` varchar(255) DEFAULT NULL,
  `before_event_address_line2` varchar(255) DEFAULT NULL,
  `before_event_city` varchar(128) DEFAULT NULL,
  `before_event_region` varchar(128) DEFAULT NULL,
  `before_event_postal_code` varchar(32) DEFAULT NULL,
  `before_event_country` varchar(64) DEFAULT NULL,
  `after_event_address_line1` varchar(255) DEFAULT NULL,
  `after_event_address_line2` varchar(255) DEFAULT NULL,
  `after_event_city` varchar(128) DEFAULT NULL,
  `after_event_region` varchar(128) DEFAULT NULL,
  `after_event_postal_code` varchar(32) DEFAULT NULL,
  `after_event_country` varchar(64) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_gift_registry_public_code` (`tenant_id`, `public_code`),
  KEY `idx_member_gift_registry_user` (`tenant_id`, `user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Member gift registries';

CREATE TABLE IF NOT EXISTS `member_gift_registry_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `registry_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `spu_id` bigint NOT NULL,
  `sku_id` bigint NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `pic_url` varchar(512) DEFAULT NULL,
  `price` int NOT NULL DEFAULT 0,
  `quantity_requested` int NOT NULL DEFAULT 1,
  `quantity_purchased` int NOT NULL DEFAULT 0,
  `priority` varchar(32) DEFAULT NULL,
  `note` varchar(1024) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_gift_registry_item_sku` (`tenant_id`, `registry_id`, `sku_id`),
  KEY `idx_member_gift_registry_item_registry` (`tenant_id`, `registry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Member gift registry items';

-- Admin route: member/gift-registry/index
-- View permission: member:gift-registry:query
-- Update permission: member:gift-registry:update
