CREATE TABLE IF NOT EXISTS `trade_carrier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `code` varchar(32) NOT NULL,
  `name` varchar(128) NOT NULL,
  `country_codes` varchar(32) NOT NULL,
  `legacy_express_id` bigint DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_carrier_code` (`tenant_id`,`code`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_logistics_provider` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `code` varchar(32) NOT NULL,
  `name` varchar(128) NOT NULL,
  `capabilities` varchar(512) NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider_code` (`tenant_id`,`code`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_shipment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `shipment_no` varchar(32) NOT NULL,
  `shipment_type` varchar(20) NOT NULL,
  `status` varchar(32) NOT NULL,
  `origin_country` char(2) NOT NULL,
  `destination_country` char(2) NOT NULL,
  `origin_timezone` varchar(64) NOT NULL,
  `destination_timezone` varchar(64) NOT NULL,
  `warehouse_id` bigint NOT NULL,
  `provider_id` bigint DEFAULT NULL,
  `estimated_delivery_at` datetime DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `last_event_occurred_at` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_no` (`tenant_id`,`shipment_no`,`deleted`),
  KEY `idx_shipment_order` (`tenant_id`,`order_id`,`deleted`),
  KEY `idx_shipment_status` (`tenant_id`,`status`,`update_time`),
  CONSTRAINT `chk_shipment_origin_country` CHECK (`origin_country` IN ('US','CA')),
  CONSTRAINT `chk_shipment_destination_country` CHECK (`destination_country` IN ('US','CA')),
  CONSTRAINT `chk_shipment_domestic` CHECK (`destination_country` = `origin_country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_shipment_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shipment_id` bigint NOT NULL,
  `order_item_id` bigint NOT NULL,
  `sku_id` bigint NOT NULL,
  `quantity` decimal(24,6) NOT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_item` (`tenant_id`,`shipment_id`,`order_item_id`,`deleted`),
  KEY `idx_shipment_item_order_item` (`tenant_id`,`order_item_id`,`deleted`),
  CONSTRAINT `chk_shipment_item_quantity` CHECK (`quantity` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_shipment_package` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shipment_id` bigint NOT NULL,
  `package_no` varchar(32) NOT NULL,
  `package_type` varchar(20) NOT NULL,
  `carrier_id` bigint DEFAULT NULL,
  `tracking_number` varchar(64) DEFAULT NULL,
  `weight` decimal(18,6) DEFAULT NULL,
  `weight_unit` varchar(4) DEFAULT NULL,
  `length` decimal(18,6) DEFAULT NULL,
  `width` decimal(18,6) DEFAULT NULL,
  `height` decimal(18,6) DEFAULT NULL,
  `dimension_unit` varchar(4) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_package_no` (`tenant_id`,`shipment_id`,`package_no`,`deleted`),
  UNIQUE KEY `uk_package_tracking` (`tenant_id`,`carrier_id`,`tracking_number`,`deleted`),
  CONSTRAINT `chk_package_weight` CHECK (`weight` IS NULL OR `weight` >= 0),
  CONSTRAINT `chk_package_dimensions` CHECK ((`length` IS NULL OR `length` >= 0) AND (`width` IS NULL OR `width` >= 0) AND (`height` IS NULL OR `height` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_shipment_leg` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shipment_id` bigint NOT NULL,
  `package_id` bigint DEFAULT NULL,
  `sequence_no` int NOT NULL,
  `leg_type` varchar(20) NOT NULL,
  `carrier_id` bigint NOT NULL,
  `provider_id` bigint NOT NULL,
  `service_level` varchar(64) DEFAULT NULL,
  `tracking_number` varchar(64) DEFAULT NULL,
  `pro_number` varchar(64) DEFAULT NULL,
  `bol_number` varchar(64) DEFAULT NULL,
  `origin_location` varchar(256) DEFAULT NULL,
  `destination_location` varchar(256) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_leg_sequence` (`tenant_id`,`shipment_id`,`sequence_no`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_tracking_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shipment_id` bigint NOT NULL,
  `package_id` bigint DEFAULT NULL,
  `shipment_leg_id` bigint DEFAULT NULL,
  `provider_id` bigint NOT NULL,
  `external_event_id` varchar(128) DEFAULT NULL,
  `event_hash` char(64) DEFAULT NULL,
  `standard_status` varchar(32) NOT NULL,
  `provider_status` varchar(128) NOT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `location` varchar(256) DEFAULT NULL,
  `occurred_at` datetime NOT NULL,
  `occurred_timezone` varchar(64) DEFAULT NULL,
  `received_at` datetime NOT NULL,
  `raw_payload_ref` varchar(256) DEFAULT NULL,
  `source` varchar(20) NOT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tracking_event_external` (`tenant_id`,`provider_id`,`external_event_id`,`deleted`),
  UNIQUE KEY `uk_tracking_event_hash` (`tenant_id`,`provider_id`,`event_hash`,`deleted`),
  KEY `idx_tracking_event_timeline` (`tenant_id`,`shipment_id`,`occurred_at`,`id`),
  CONSTRAINT `chk_tracking_event_identity` CHECK (`external_event_id` IS NOT NULL OR `event_hash` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_order_fulfillment_summary` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `status` varchar(32) NOT NULL,
  `shipment_count` int NOT NULL DEFAULT 0,
  `delivered_shipment_count` int NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_fulfillment_summary` (`tenant_id`,`order_id`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_fulfillment_idempotency` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `operation` varchar(64) NOT NULL,
  `idempotency_key_hash` char(64) NOT NULL,
  `request_hash` char(64) NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `resource_id` bigint DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `expires_at` datetime NOT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fulfillment_idempotency` (`tenant_id`,`operation`,`idempotency_key_hash`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `trade_fulfillment_outbox_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `event_id` char(36) NOT NULL,
  `aggregate_type` varchar(32) NOT NULL,
  `aggregate_id` bigint NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `payload` json NOT NULL,
  `status` varchar(16) NOT NULL,
  `attempt_count` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime NOT NULL,
  `published_at` datetime DEFAULT NULL,
  `last_error_code` varchar(64) DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fulfillment_outbox_event_id` (`tenant_id`,`event_id`,`deleted`),
  KEY `idx_fulfillment_outbox_due` (`tenant_id`,`status`,`next_attempt_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
