SET NAMES utf8mb4;
SET @tenant_id := 121;
-- Local furniture/Yudao custom module tables.

CREATE TABLE IF NOT EXISTS `member_trade_application` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `business_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Business name',
  `country` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Country',
  `street` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Street',
  `address2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Address line 2',
  `city` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'City',
  `state` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'State',
  `postal_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Postal code',
  `business_description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Business description',
  `website` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Website',
  `portfolio` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Portfolio',
  `instagram` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Instagram',
  `pinterest` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Pinterest',
  `houzz` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Houzz',
  `linkedin` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'LinkedIn',
  `primary_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Primary email',
  `authorized_users_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Authorized users JSON',
  `business_documents_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Business documents JSON',
  `tax_documents_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Tax documents JSON',
  `email_opt_in` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Email opt-in',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT 'Status: 0 pending, 1 approved, 2 rejected',
  `trade_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Trade ID',
  `review_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Review reason',
  `review_time` datetime NULL DEFAULT NULL COMMENT 'Review time',
  `reviewer_id` bigint NULL DEFAULT NULL COMMENT 'Reviewer ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_primary_email` (`primary_email` ASC) USING BTREE,
  INDEX `idx_status` (`status` ASC) USING BTREE,
  INDEX `idx_trade_id` (`trade_id` ASC) USING BTREE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Member trade application';

CREATE TABLE IF NOT EXISTS `product_brand` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Brand name',
  `pic_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Brand image',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `description` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Description',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT 'Status',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_product_brand_tenant_name_deleted` (`tenant_id`, `name`, `deleted`) USING BTREE,
  KEY `idx_product_brand_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Product brand';

CREATE TABLE IF NOT EXISTS `product_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT 'Parent category ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Category name',
  `pic_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Category image',
  `big_pic_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Large category image',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT 'Status',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_product_category_tenant_parent_name_deleted` (`tenant_id`, `parent_id`, `name`, `deleted`) USING BTREE,
  KEY `idx_product_category_tenant_parent` (`tenant_id`, `parent_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Product category';

CREATE TABLE IF NOT EXISTS `product_spu` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'SPU name',
  `keyword` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Keyword',
  `introduction` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Introduction',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Description',
  `category_id` bigint NOT NULL DEFAULT 0 COMMENT 'Category ID',
  `brand_id` bigint NOT NULL DEFAULT 0 COMMENT 'Brand ID',
  `pic_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Cover image',
  `slider_pic_urls` json NULL COMMENT 'Slider images',
  `detail_config` json NULL COMMENT 'Furniture detail config',
  `unit` int NOT NULL DEFAULT 1 COMMENT 'Unit',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT 'Status',
  `spec_type` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Spec type',
  `price` int NOT NULL DEFAULT 0 COMMENT 'Price in fen',
  `market_price` int NOT NULL DEFAULT 0 COMMENT 'Market price in fen',
  `cost_price` int NOT NULL DEFAULT 0 COMMENT 'Cost price in fen',
  `stock` int NOT NULL DEFAULT 0 COMMENT 'Stock',
  `delivery_types` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '1' COMMENT 'Delivery types',
  `delivery_template_id` bigint NOT NULL DEFAULT 0 COMMENT 'Delivery template ID',
  `recommend_hot` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Recommend hot',
  `recommend_benefit` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Recommend benefit',
  `recommend_best` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Recommend best',
  `recommend_new` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Recommend new',
  `recommend_good` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Recommend good',
  `give_integral` int NOT NULL DEFAULT 0 COMMENT 'Give integral',
  `sub_commission_type` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Sub commission type',
  `sales_count` int NOT NULL DEFAULT 0 COMMENT 'Sales count',
  `virtual_sales_count` int NOT NULL DEFAULT 0 COMMENT 'Virtual sales count',
  `browse_count` int NOT NULL DEFAULT 0 COMMENT 'Browse count',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_product_spu_tenant_keyword_deleted` (`tenant_id`, `keyword`, `deleted`) USING BTREE,
  KEY `idx_product_spu_tenant_status` (`tenant_id`, `status`) USING BTREE,
  KEY `idx_product_spu_tenant_category` (`tenant_id`, `category_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Product SPU';

CREATE TABLE IF NOT EXISTS `product_sku` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `spu_id` bigint NOT NULL COMMENT 'SPU ID',
  `properties` json NULL COMMENT 'Properties',
  `price` int NOT NULL DEFAULT 0 COMMENT 'Price in fen',
  `market_price` int NOT NULL DEFAULT 0 COMMENT 'Market price in fen',
  `cost_price` int NOT NULL DEFAULT 0 COMMENT 'Cost price in fen',
  `bar_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Bar code',
  `pic_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Image',
  `stock` int NOT NULL DEFAULT 0 COMMENT 'Stock',
  `weight` double NOT NULL DEFAULT 0 COMMENT 'Weight',
  `volume` double NOT NULL DEFAULT 0 COMMENT 'Volume',
  `first_brokerage_price` int NOT NULL DEFAULT 0 COMMENT 'First brokerage price',
  `second_brokerage_price` int NOT NULL DEFAULT 0 COMMENT 'Second brokerage price',
  `sales_count` int NOT NULL DEFAULT 0 COMMENT 'Sales count',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_product_sku_tenant_spu_deleted` (`tenant_id`, `spu_id`, `deleted`) USING BTREE,
  KEY `idx_product_sku_tenant_spu` (`tenant_id`, `spu_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Product SKU';


INSERT INTO product_brand(name, pic_url, sort, description, status, creator, updater, tenant_id)
VALUES ('Trendz Demo', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 10, 'Demo brand for furniture assistant testing', 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), sort = VALUES(sort), description = VALUES(description), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @brand_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (0, 'Furniture Agent Demo', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 10, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @root_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Sofas', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 20, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @sofa_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Dining Tables', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 30, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @dining_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Dining Chairs', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 35, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @dining_chair_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Coffee Tables', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 36, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @coffee_table_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Beds', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 40, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @bedroom_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Desks', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 45, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @office_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Rugs', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 46, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @rug_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Bedroom Storage', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 47, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @bedroom_storage_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Wardrobes', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 48, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @wardrobe_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Side Tables', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 49, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @side_table_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Lighting', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 50, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @lighting_category_id := LAST_INSERT_ID();

INSERT INTO product_category(parent_id, name, pic_url, big_pic_url, sort, status, creator, updater, tenant_id)
VALUES (@root_category_id, 'Media Storage', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', 60, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), pic_url = VALUES(pic_url), big_pic_url = VALUES(big_pic_url), sort = VALUES(sort), status = VALUES(status), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @storage_category_id := LAST_INSERT_ID();

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('Cream Fabric Sofa', 'sofa cream fabric living room under 8000', 'Cream performance fabric sofa with deep cushions for living rooms and budgets under 8000.', '<p>Cream performance fabric sofa with deep cushions for living rooms and budgets under 8000.</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 699900, 899900, 420000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 699900, 899900, 420000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('Cloud Modular Sofa', 'sofa modular cloud fabric living room', 'Low, deep modular sofa with down-blend cushions for flexible living room layouts.', '<p>Low, deep modular sofa with down-blend cushions for flexible living room layouts.</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 329900, 459900, 220000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 329900, 459900, 220000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('Leather Lounge Sofa', 'sofa leather lounge living room', 'Warm brown leather sofa for premium living rooms, studies, and lounge seating.', '<p>Warm brown leather sofa for premium living rooms, studies, and lounge seating.</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1678225179685-b8ad3b6d7249?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1678225179685-b8ad3b6d7249?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 1299900, 1599900, 780000, 8, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 1299900, 1599900, 780000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1678225179685-b8ad3b6d7249?auto=format&fit=crop&w=1200&q=80', 8, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('米白布艺沙发 Sofa', 'sofa 米白布艺沙发 cream fabric living room under 8000', '米白色亲肤布艺，适合客厅和小户型，预算 8000 元内可推荐。', '<p>米白色亲肤布艺，适合客厅和小户型，预算 8000 元内可推荐。</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 699900, 899900, 420000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 699900, 899900, 420000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1768144092684-c1a5dd6c7aad?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('小户型沙发 Sofa', 'sofa 小户型沙发 compact apartment small living room under 5000', '紧凑尺寸，适合公寓、小客厅和预算筛选场景。', '<p>紧凑尺寸，适合公寓、小客厅和预算筛选场景。</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 329900, 459900, 220000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 329900, 459900, 220000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('皮沙发 Sofa', 'sofa 皮沙发 leather lounge living room premium', '暖棕皮质沙发，适合客厅、书房和高质感推荐。', '<p>暖棕皮质沙发，适合客厅、书房和高质感推荐。</p>', @sofa_category_id, @brand_id, 'https://images.unsplash.com/photo-1616593871468-2a9452218369?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1616593871468-2a9452218369?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 1299900, 1599900, 780000, 8, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 1299900, 1599900, 780000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1616593871468-2a9452218369?auto=format&fit=crop&w=1200&q=80', 8, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('餐桌 Dining Table', 'table 餐桌 dining table family dinner under 6000', '六人位餐桌，适合餐厅、家庭聚餐和中等预算推荐。', '<p>六人位餐桌，适合餐厅、家庭聚餐和中等预算推荐。</p>', @dining_category_id, @brand_id, 'https://images.unsplash.com/photo-1730630906214-1256b57d65b7?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1730630906214-1256b57d65b7?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 459900, 599900, 260000, 12, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 459900, 599900, 260000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1730630906214-1256b57d65b7?auto=format&fit=crop&w=1200&q=80', 12, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('床 Bed', 'bed 床 bedroom upholstered queen under 7000', '软包双人床，适合卧室搭配和预算筛选。', '<p>软包双人床，适合卧室搭配和预算筛选。</p>', @bedroom_category_id, @brand_id, 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 529900, 699900, 310000, 10, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 529900, 699900, 310000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', 10, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('吊灯 Lighting', 'lighting lamp 吊灯 pendant light dining room under 3000', '金属吊灯，适合餐厅、客厅和氛围照明推荐。', '<p>金属吊灯，适合餐厅、客厅和氛围照明推荐。</p>', @lighting_category_id, @brand_id, 'https://images.unsplash.com/photo-1721523262897-49620a979091?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1721523262897-49620a979091?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 189900, 259900, 90000, 25, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 189900, 259900, 90000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1721523262897-49620a979091?auto=format&fit=crop&w=1200&q=80', 25, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('电视柜 Cabinet', 'cabinet 电视柜 media console living room under 5000', '低矮电视柜，适合客厅收纳和电视墙搭配。', '<p>低矮电视柜，适合客厅收纳和电视墙搭配。</p>', @storage_category_id, @brand_id, 'https://images.unsplash.com/photo-1646861039459-fd9e3aabf3fb?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1646861039459-fd9e3aabf3fb?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 359900, 499900, 190000, 14, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 359900, 499900, 190000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1646861039459-fd9e3aabf3fb?auto=format&fit=crop&w=1200&q=80', 14, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('黑色圆形餐桌 Dining Table', 'dining table 黑色圆形餐桌 black round dining room under 6000', '黑色圆形餐桌，适合现代餐厅和四人位小家庭用餐场景。', '<p>黑色圆形餐桌，适合现代餐厅和四人位小家庭用餐场景。</p>', @dining_category_id, @brand_id, 'https://images.unsplash.com/photo-1729606312336-63d202c090b1?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1729606312336-63d202c090b1?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 569900, 699900, 320000, 9, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 569900, 699900, 320000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1729606312336-63d202c090b1?auto=format&fit=crop&w=1200&q=80', 9, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('原木长餐桌 Dining Table', 'dining table 原木长餐桌 wood family dining room under 7000', '原木色长餐桌，适合六到八人位家庭餐厅和温暖木质风格。', '<p>原木色长餐桌，适合六到八人位家庭餐厅和温暖木质风格。</p>', @dining_category_id, @brand_id, 'https://images.unsplash.com/photo-1758977403438-1b8546560d31?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1758977403438-1b8546560d31?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 599900, 759900, 350000, 7, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 599900, 759900, 350000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1758977403438-1b8546560d31?auto=format&fit=crop&w=1200&q=80', 7, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('灰色软包餐椅 Chair', 'chair 灰色软包餐椅 dining chair fabric wood legs under 1500', '灰色布艺软包餐椅，搭配木质桌脚，适合餐厅补椅和小预算场景。', '<p>灰色布艺软包餐椅，搭配木质桌脚，适合餐厅补椅和小预算场景。</p>', @dining_chair_category_id, @brand_id, 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 89900, 129900, 42000, 32, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 89900, 129900, 42000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', 32, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('黑色现代餐椅 Chair', 'chair 黑色餐椅 dining chair modern black under 2000', '黑色现代餐椅，适合黑色餐桌、极简餐厅和套装搭配。', '<p>黑色现代餐椅，适合黑色餐桌、极简餐厅和套装搭配。</p>', @dining_chair_category_id, @brand_id, 'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 129900, 179900, 58000, 24, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 129900, 179900, 58000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=80', 24, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('黑色玻璃茶几 Coffee Table', 'coffee table 黑色玻璃茶几 living room rug under 3000', '黑色玻璃茶几，适合现代客厅、浅色沙发和米色地毯搭配。', '<p>黑色玻璃茶几，适合现代客厅、浅色沙发和米色地毯搭配。</p>', @coffee_table_category_id, @brand_id, 'https://images.unsplash.com/photo-1609766857120-0183863c7971?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1609766857120-0183863c7971?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 249900, 329900, 125000, 15, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 249900, 329900, 125000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1609766857120-0183863c7971?auto=format&fit=crop&w=1200&q=80', 15, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('原木茶几 Coffee Table', 'coffee table 原木茶几 wood living room under 2500', '原木色茶几，木纹清晰，适合日式、北欧和自然风客厅。', '<p>原木色茶几，木纹清晰，适合日式、北欧和自然风客厅。</p>', @coffee_table_category_id, @brand_id, 'https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 219900, 299900, 110000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 219900, 299900, 110000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('棕色木质边几 Side Table', 'side table 棕色木质边几 living room sofa side under 1500', '棕色木质边几，适合沙发旁、床边和小角落收纳场景。', '<p>棕色木质边几，适合沙发旁、床边和小角落收纳场景。</p>', @side_table_category_id, @brand_id, 'https://images.unsplash.com/photo-1565374369705-acde12f3caa2?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1565374369705-acde12f3caa2?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 129900, 169900, 62000, 20, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 129900, 169900, 62000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1565374369705-acde12f3caa2?auto=format&fit=crop&w=1200&q=80', 20, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('胡桃木书桌 Desk', 'desk 胡桃木书桌 home office walnut under 5000', '胡桃木书桌，适合居家办公、书房和显示器办公桌搭配。', '<p>胡桃木书桌，适合居家办公、书房和显示器办公桌搭配。</p>', @office_category_id, @brand_id, 'https://images.unsplash.com/photo-1575318633968-0383e7d07ca0?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1575318633968-0383e7d07ca0?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 399900, 529900, 210000, 11, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 399900, 529900, 210000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1575318633968-0383e7d07ca0?auto=format&fit=crop&w=1200&q=80', 11, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('米色羊毛地毯 Rug', 'rug 米色羊毛地毯 living room beige under 2500', '米色羊毛地毯，适合浅色沙发、茶几和现代客厅软装。', '<p>米色羊毛地毯，适合浅色沙发、茶几和现代客厅软装。</p>', @rug_category_id, @brand_id, 'https://images.unsplash.com/photo-1520762042279-ae3264026bd2?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1520762042279-ae3264026bd2?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 189900, 259900, 90000, 16, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 189900, 259900, 90000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1520762042279-ae3264026bd2?auto=format&fit=crop&w=1200&q=80', 16, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('灰色纹理地毯 Rug', 'rug 灰色纹理地毯 living room gray under 2000', '灰色纹理地毯，适合黑色餐桌、客厅休闲区和低饱和配色。', '<p>灰色纹理地毯，适合黑色餐桌、客厅休闲区和低饱和配色。</p>', @rug_category_id, @brand_id, 'https://images.unsplash.com/photo-1618220252344-8ec99ec624b1?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1618220252344-8ec99ec624b1?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 159900, 219900, 78000, 19, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 159900, 219900, 78000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1618220252344-8ec99ec624b1?auto=format&fit=crop&w=1200&q=80', 19, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('木质床头柜 Nightstand', 'nightstand 木质床头柜 bedroom lamp under 2000', '木质床头柜，搭配球形台灯和软包床，适合卧室收纳。', '<p>木质床头柜，搭配球形台灯和软包床，适合卧室收纳。</p>', @bedroom_storage_category_id, @brand_id, 'https://images.unsplash.com/photo-1565374235393-6fe32a07cc86?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1565374235393-6fe32a07cc86?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 149900, 199900, 72000, 18, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 149900, 199900, 72000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1565374235393-6fe32a07cc86?auto=format&fit=crop&w=1200&q=80', 18, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('胡桃木斗柜 Dresser', 'dresser 胡桃木斗柜 bedroom storage under 4000', '胡桃木斗柜，适合卧室衣物收纳、走廊和复古木质风格。', '<p>胡桃木斗柜，适合卧室衣物收纳、走廊和复古木质风格。</p>', @bedroom_storage_category_id, @brand_id, 'https://images.unsplash.com/photo-1579283111509-855c7eea1c49?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1579283111509-855c7eea1c49?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 299900, 399900, 150000, 10, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 299900, 399900, 150000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1579283111509-855c7eea1c49?auto=format&fit=crop&w=1200&q=80', 10, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('原木衣柜 Wardrobe', 'wardrobe 原木衣柜 closet bedroom storage under 8000', '原木色衣柜，带挂衣区和抽屉收纳，适合卧室或衣帽间。', '<p>原木色衣柜，带挂衣区和抽屉收纳，适合卧室或衣帽间。</p>', @wardrobe_category_id, @brand_id, 'https://images.unsplash.com/photo-1778731660303-1fa5ede75477?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1778731660303-1fa5ede75477?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 699900, 899900, 380000, 6, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 699900, 899900, 380000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1778731660303-1fa5ede75477?auto=format&fit=crop&w=1200&q=80', 6, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('白色球形台灯 Table Lamp', 'table lamp 白色球形台灯 bedside nightstand under 1000', '白色球形台灯，适合床头柜、卧室氛围和柔和夜间照明。', '<p>白色球形台灯，适合床头柜、卧室氛围和柔和夜间照明。</p>', @lighting_category_id, @brand_id, 'https://images.unsplash.com/photo-1753932847231-7949af383b98?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1753932847231-7949af383b98?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 89900, 129900, 36000, 26, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 89900, 129900, 36000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1753932847231-7949af383b98?auto=format&fit=crop&w=1200&q=80', 26, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('黑色落地灯 Floor Lamp', 'floor lamp 黑色落地灯 living room sofa under 2000', '黑色落地灯，适合沙发旁边、阅读角和客厅辅助照明。', '<p>黑色落地灯，适合沙发旁边、阅读角和客厅辅助照明。</p>', @lighting_category_id, @brand_id, 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 169900, 229900, 82000, 21, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 169900, 229900, 82000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80', 21, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

INSERT INTO product_spu(name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls, unit, sort, status, spec_type, price, market_price, cost_price, stock, delivery_types, delivery_template_id, recommend_hot, recommend_benefit, recommend_best, recommend_new, recommend_good, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count, creator, updater, tenant_id)
VALUES ('胡桃木餐边柜 Cabinet', 'cabinet 胡桃木餐边柜 sideboard dining storage under 4000', '胡桃木餐边柜，适合餐厅餐具收纳、客厅陈列和木质风格。', '<p>胡桃木餐边柜，适合餐厅餐具收纳、客厅陈列和木质风格。</p>', @storage_category_id, @brand_id, 'https://images.unsplash.com/photo-1713810958247-01dbd76b4a61?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1713810958247-01dbd76b4a61?auto=format&fit=crop&w=1200&q=80"]', 1, 100, 1, b'0', 329900, 449900, 170000, 12, '1', 0, b'1', b'0', b'1', b'1', b'1', 0, b'0', 0, 0, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), name = VALUES(name), introduction = VALUES(introduction), description = VALUES(description), category_id = VALUES(category_id), brand_id = VALUES(brand_id), pic_url = VALUES(pic_url), slider_pic_urls = VALUES(slider_pic_urls), unit = VALUES(unit), sort = VALUES(sort), status = VALUES(status), spec_type = VALUES(spec_type), price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), stock = VALUES(stock), delivery_types = VALUES(delivery_types), delivery_template_id = VALUES(delivery_template_id), recommend_hot = VALUES(recommend_hot), recommend_benefit = VALUES(recommend_benefit), recommend_best = VALUES(recommend_best), recommend_new = VALUES(recommend_new), recommend_good = VALUES(recommend_good), give_integral = VALUES(give_integral), sub_commission_type = VALUES(sub_commission_type), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;
SET @spu_id := LAST_INSERT_ID();
INSERT INTO product_sku(spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume, sales_count, creator, updater, tenant_id)
VALUES (@spu_id, '[]', 329900, 449900, 170000, CONCAT('FA-', @spu_id), 'https://images.unsplash.com/photo-1713810958247-01dbd76b4a61?auto=format&fit=crop&w=1200&q=80', 12, 35.0, 1.6, 0, 'furniture-agent-seed', 'furniture-agent-seed', @tenant_id)
ON DUPLICATE KEY UPDATE price = VALUES(price), market_price = VALUES(market_price), cost_price = VALUES(cost_price), bar_code = VALUES(bar_code), pic_url = VALUES(pic_url), stock = VALUES(stock), updater = VALUES(updater), update_time = CURRENT_TIMESTAMP;

SELECT COUNT(*) AS seeded_product_count FROM product_spu WHERE tenant_id = @tenant_id AND creator = 'furniture-agent-seed' AND status = 1 AND deleted = b'0';
SELECT id, name, price, stock FROM product_spu WHERE tenant_id = @tenant_id AND creator = 'furniture-agent-seed' AND status = 1 AND deleted = b'0' ORDER BY price ASC LIMIT 10;