CREATE TABLE IF NOT EXISTS "product_statistics" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "time" date NOT NULL, "spu_id" bigint NOT NULL,
  "browse_count" int NOT NULL DEFAULT 0, "browse_user_count" int NOT NULL DEFAULT 0,
  "favorite_count" int NOT NULL DEFAULT 0, "cart_count" int NOT NULL DEFAULT 0,
  "order_count" int NOT NULL DEFAULT 0, "order_pay_count" int NOT NULL DEFAULT 0,
  "order_pay_price" bigint NOT NULL DEFAULT 0, "after_sale_count" int NOT NULL DEFAULT 0,
  "after_sale_refund_price" bigint NOT NULL DEFAULT 0, "browse_convert_percent" int NOT NULL DEFAULT 0,
  "known_cost_amount" bigint NOT NULL DEFAULT 0, "cost_amount" bigint,
  "gross_profit" bigint, "gross_margin_percent" decimal(12,4),
  "exact_cost_item_count" bigint NOT NULL DEFAULT 0,
  "estimated_cost_item_count" bigint NOT NULL DEFAULT 0,
  "missing_cost_item_count" bigint NOT NULL DEFAULT 0,
  "profit_data_quality" tinyint NOT NULL DEFAULT 5,
  "traffic_data_status" tinyint NOT NULL DEFAULT 3, "traffic_watermark" timestamp,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"), UNIQUE ("tenant_id", "time", "spu_id")
);

CREATE TABLE IF NOT EXISTS "statistics_dashboard_hmac_day" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "day" date NOT NULL,
  "hash_key_version" smallint NOT NULL, "activated_at" timestamp NOT NULL, "destroy_after" timestamp,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"), UNIQUE ("tenant_id","day"), UNIQUE ("tenant_id","day","hash_key_version")
);

CREATE TABLE IF NOT EXISTS "statistics_behavior_event" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "event_id" varchar(64) NOT NULL,
  "event_type" tinyint NOT NULL, "event_source" tinyint NOT NULL,
  "visitor_hash" char(64) NOT NULL, "session_hash" char(64), "hash_key_version" smallint NOT NULL,
  "user_id" bigint, "spu_id" bigint, "sku_id" bigint, "quantity" int,
  "page_path" varchar(255) NOT NULL, "referrer_host" varchar(255), "device_type" tinyint NOT NULL DEFAULT 9,
  "traffic_quality" tinyint NOT NULL DEFAULT 1, "exclusion_reason" varchar(64),
  "occurred_at" timestamp NOT NULL, "event_day" date NOT NULL,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"), UNIQUE ("tenant_id","event_id"),
  FOREIGN KEY ("tenant_id","event_day","hash_key_version") REFERENCES "statistics_dashboard_hmac_day"("tenant_id","day","hash_key_version")
);

CREATE TABLE IF NOT EXISTS "statistics_behavior_ingestion_gap" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "day" date NOT NULL,
  "reason_code" varchar(64) NOT NULL, "bucket_start" timestamp NOT NULL,
  "first_seen_at" timestamp NOT NULL, "last_seen_at" timestamp NOT NULL, "rejected_count" bigint NOT NULL,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"), UNIQUE ("tenant_id","day","reason_code","bucket_start")
);

CREATE TABLE IF NOT EXISTS "statistics_traffic_daily" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "day" date NOT NULL, "currency_code" char(3) NOT NULL,
  "home_pv" bigint, "home_uv" bigint, "product_detail_pv" bigint, "product_detail_uv" bigint,
  "add_cart_count" bigint, "add_cart_user_count" bigint, "checkout_start_count" bigint,
  "paid_order_count" bigint NOT NULL DEFAULT 0, "paid_buyer_count" bigint NOT NULL DEFAULT 0,
  "paid_item_count" bigint NOT NULL DEFAULT 0, "paid_revenue" bigint NOT NULL DEFAULT 0,
  "refund_amount" bigint NOT NULL DEFAULT 0, "net_revenue" bigint NOT NULL DEFAULT 0,
  "known_cost_amount" bigint NOT NULL DEFAULT 0, "cost_amount" bigint, "gross_profit" bigint,
  "gross_margin_percent" decimal(12,4), "exact_cost_item_count" bigint NOT NULL DEFAULT 0,
  "estimated_cost_item_count" bigint NOT NULL DEFAULT 0, "missing_cost_item_count" bigint NOT NULL DEFAULT 0,
  "profit_data_quality" tinyint NOT NULL DEFAULT 5, "accepted_event_count" bigint NOT NULL DEFAULT 0,
  "excluded_event_count" bigint NOT NULL DEFAULT 0, "traffic_data_status" tinyint NOT NULL DEFAULT 3,
  "traffic_watermark" timestamp, "trade_watermark" timestamp, "refund_watermark" timestamp,
  "last_successful_run_at" timestamp,
  "creator" varchar DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"), UNIQUE ("tenant_id","day")
);
