CREATE TABLE IF NOT EXISTS `product_furniture_sku_search` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `spu_id` bigint NOT NULL,
  `sku_id` bigint NOT NULL,
  `category_code` varchar(32) NOT NULL,
  `style_codes` json NOT NULL,
  `color_code` varchar(32) DEFAULT NULL,
  `material_codes` json NOT NULL,
  `seat_count` int DEFAULT NULL,
  `width_mm` int DEFAULT NULL,
  `depth_mm` int DEFAULT NULL,
  `height_mm` int DEFAULT NULL,
  `room_type_codes` json NOT NULL,
  `feature_codes` json NOT NULL,
  `pet_friendly` bit(1) NOT NULL DEFAULT b'0',
  `child_friendly` bit(1) NOT NULL DEFAULT b'0',
  `easy_clean` bit(1) NOT NULL DEFAULT b'0',
  `scratch_resistant` bit(1) NOT NULL DEFAULT b'0',
  `movable` bit(1) NOT NULL DEFAULT b'0',
  `rental_friendly` bit(1) NOT NULL DEFAULT b'0',
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_sku` (`tenant_id`, `sku_id`),
  KEY `idx_tenant_category` (`tenant_id`, `category_code`),
  KEY `idx_dimensions` (`tenant_id`, `category_code`, `width_mm`, `depth_mm`, `height_mm`),
  KEY `idx_seat_count` (`tenant_id`, `category_code`, `seat_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Furniture SKU typed search projection';
