package cn.iocoder.yudao.module.statistics.service.dashboard;
import cn.iocoder.yudao.framework.common.pojo.PageResult;import cn.iocoder.yudao.module.product.api.spu.ProductSpuApi;import cn.iocoder.yudao.module.product.api.spu.dto.ProductSpuRespDTO;import cn.iocoder.yudao.module.statistics.controller.admin.dashboard.vo.*;import cn.iocoder.yudao.module.statistics.dal.dataobject.dashboard.TrafficDailyDO;import cn.iocoder.yudao.module.statistics.dal.dataobject.product.ProductStatisticsDO;import cn.iocoder.yudao.module.statistics.dal.mysql.dashboard.TrafficDailyMapper;import cn.iocoder.yudao.module.statistics.dal.mysql.product.ProductStatisticsMapper;import org.junit.jupiter.api.Test;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import java.util.*;import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class DashboardQueryServiceImplTest {
 @Test void ordinaryQuery_omitsProfitAndKeepsUnknownTraffic(){TrafficDailyMapper traffic=mock(TrafficDailyMapper.class);ProductStatisticsMapper products=mock(ProductStatisticsMapper.class);when(traffic.selectBetween(any(),any())).thenReturn(Collections.singletonList(new TrafficDailyDO().setDay(LocalDate.now().minusDays(1)).setProductDetailPv(null).setPaidOrderCount(3L).setPaidRevenue(1000L).setKnownCostAmount(500L).setCostAmount(500L).setGrossProfit(500L).setTrafficDataStatus(3)));DashboardQueryServiceImpl s=service(traffic,products);DashboardSummaryRespVO result=s.summary(new DashboardQueryReqVO(),false);assertFalse(result.getProfitVisible());assertNull(result.getKnownCostAmount());assertNull(result.getGrossProfit());assertNull(result.getBrowseOrderConversionPercent());assertEquals("UNAVAILABLE",result.getTrafficDataStatus());}
 @Test void profitPermission_exposesProfitWithoutClampingConversion(){TrafficDailyMapper traffic=mock(TrafficDailyMapper.class);when(traffic.selectBetween(any(),any())).thenReturn(Collections.singletonList(new TrafficDailyDO().setProductDetailPv(2L).setPaidOrderCount(3L).setPaidRevenue(1000L).setRefundAmount(0L).setKnownCostAmount(400L).setMissingCostItemCount(0L).setTrafficDataStatus(1).setTrafficWatermark(LocalDateTime.now())));DashboardSummaryRespVO result=service(traffic,mock(ProductStatisticsMapper.class)).summary(new DashboardQueryReqVO(),true);assertEquals(new java.math.BigDecimal("150.00"),result.getBrowseOrderConversionPercent());assertEquals(Long.valueOf(600),result.getGrossProfit());}
 @Test void siteScope_rejectsProductFilter(){DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("SITE").setSpuId(1L);assertThrows(IllegalArgumentException.class,()->service(mock(TrafficDailyMapper.class),mock(ProductStatisticsMapper.class)).summary(q,false));}
 @Test void productPage_aggregatesEnrichesSortsAndReturnsTotal(){ProductStatisticsMapper mapper=mock(ProductStatisticsMapper.class);when(mapper.selectBetween(any(),any())).thenReturn(Arrays.asList(row(1L,40),row(2L,90),row(1L,70)));ProductSpuApi api=mock(ProductSpuApi.class);when(api.getSpuList(anyCollection())).thenReturn(success(Arrays.asList(spu(1L,8L,"Oak chair"),spu(2L,9L,"Linen sofa"))));DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("PRODUCT").setSortField("browseCount").setSortOrder("desc").setPageNo(1).setPageSize(1);PageResult<DashboardProductRespVO> page=service(mock(TrafficDailyMapper.class),mapper,api).productPage(q,false);assertEquals(Long.valueOf(2),page.getTotal());assertEquals(1,page.getList().size());assertEquals("Oak chair",page.getList().get(0).getProductName());assertEquals(Integer.valueOf(110),page.getList().get(0).getBrowseCount());}
 @Test void productPage_rejectsSpuOutsideSelectedCategory(){ProductStatisticsMapper mapper=mock(ProductStatisticsMapper.class);when(mapper.selectBetween(any(),any())).thenReturn(Collections.singletonList(row(1L,40)));ProductSpuApi api=mock(ProductSpuApi.class);when(api.getSpuList(anyCollection())).thenReturn(success(Collections.singletonList(spu(1L,8L,"Oak chair"))));DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("PRODUCT").setCategoryId(9L).setSpuId(1L);assertThrows(IllegalArgumentException.class,()->service(mock(TrafficDailyMapper.class),mapper,api).productPage(q,false));}
 @Test void productCategoryFilterAppliesToSummaryAsWellAsTheTable(){ProductStatisticsMapper mapper=mock(ProductStatisticsMapper.class);when(mapper.selectBetween(any(),any())).thenReturn(Arrays.asList(row(1L,40),row(2L,90)));ProductSpuApi api=mock(ProductSpuApi.class);when(api.getSpuList(anyCollection())).thenReturn(success(Arrays.asList(spu(1L,8L,"Oak chair"),spu(2L,9L,"Linen sofa"))));DashboardSummaryRespVO summary=service(mock(TrafficDailyMapper.class),mapper,api).summary(new DashboardQueryReqVO().setScope("PRODUCT").setCategoryId(8L),false);assertEquals(Long.valueOf(40L),summary.getProductDetailPv());}
 @Test void productPageAppliesTheSelectedOperationalRiskView(){ProductStatisticsMapper mapper=mock(ProductStatisticsMapper.class);when(mapper.selectBetween(any(),any())).thenReturn(Arrays.asList(row(1L,120),row(2L,30)));ProductSpuApi api=mock(ProductSpuApi.class);when(api.getSpuList(anyCollection())).thenReturn(success(Arrays.asList(spu(1L,8L,"Oak chair"),spu(2L,9L,"Linen sofa"))));PageResult<DashboardProductRespVO> page=service(mock(TrafficDailyMapper.class),mapper,api).productPage(new DashboardQueryReqVO().setScope("PRODUCT").setRiskType("HIGH_TRAFFIC_LOW_CONVERSION"),false);assertEquals(Long.valueOf(1),page.getTotal());assertEquals(Long.valueOf(1),page.getList().get(0).getSpuId());}
 @Test void productPage_rejectsUnknownSortField(){DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("PRODUCT").setSortField("deleted desc");assertThrows(IllegalArgumentException.class,()->service(mock(TrafficDailyMapper.class),mock(ProductStatisticsMapper.class)).products(q,false));}
 private ProductStatisticsDO row(Long spu,int views){return new ProductStatisticsDO().setSpuId(spu).setBrowseCount(views).setTrafficDataStatus(1).setProfitDataQuality(1);}
 private ProductSpuRespDTO spu(Long id,Long category,String name){return new ProductSpuRespDTO().setId(id).setCategoryId(category).setName(name).setPicUrl("https://example.test/"+id+".jpg");}
 private DashboardQueryServiceImpl service(TrafficDailyMapper t,ProductStatisticsMapper p){DashboardQueryServiceImpl s=new DashboardQueryServiceImpl();ReflectionTestUtils.setField(s,"trafficMapper",t);ReflectionTestUtils.setField(s,"productMapper",p);return s;}
 private DashboardQueryServiceImpl service(TrafficDailyMapper t,ProductStatisticsMapper p,ProductSpuApi api){DashboardQueryServiceImpl s=service(t,p);ReflectionTestUtils.setField(s,"productSpuApi",api);return s;}
}
