package cn.iocoder.yudao.module.statistics.service.dashboard;
import cn.iocoder.yudao.module.statistics.controller.admin.dashboard.vo.*;import cn.iocoder.yudao.module.statistics.dal.dataobject.dashboard.TrafficDailyDO;import cn.iocoder.yudao.module.statistics.dal.dataobject.product.ProductStatisticsDO;import cn.iocoder.yudao.module.statistics.dal.mysql.dashboard.TrafficDailyMapper;import cn.iocoder.yudao.module.statistics.dal.mysql.product.ProductStatisticsMapper;import org.junit.jupiter.api.Test;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class DashboardQueryServiceImplTest {
 @Test void ordinaryQuery_omitsProfitAndKeepsUnknownTraffic(){TrafficDailyMapper traffic=mock(TrafficDailyMapper.class);ProductStatisticsMapper products=mock(ProductStatisticsMapper.class);when(traffic.selectBetween(any(),any())).thenReturn(Collections.singletonList(new TrafficDailyDO().setDay(LocalDate.now().minusDays(1)).setProductDetailPv(null).setPaidOrderCount(3L).setPaidRevenue(1000L).setKnownCostAmount(500L).setCostAmount(500L).setGrossProfit(500L).setTrafficDataStatus(3)));DashboardQueryServiceImpl s=service(traffic,products);DashboardSummaryRespVO result=s.summary(new DashboardQueryReqVO(),false);assertFalse(result.getProfitVisible());assertNull(result.getKnownCostAmount());assertNull(result.getGrossProfit());assertNull(result.getBrowseOrderConversionPercent());assertEquals("UNAVAILABLE",result.getTrafficDataStatus());}
 @Test void profitPermission_exposesProfitWithoutClampingConversion(){TrafficDailyMapper traffic=mock(TrafficDailyMapper.class);when(traffic.selectBetween(any(),any())).thenReturn(Collections.singletonList(new TrafficDailyDO().setProductDetailPv(2L).setPaidOrderCount(3L).setPaidRevenue(1000L).setRefundAmount(0L).setKnownCostAmount(400L).setMissingCostItemCount(0L).setTrafficDataStatus(1).setTrafficWatermark(LocalDateTime.now())));DashboardSummaryRespVO result=service(traffic,mock(ProductStatisticsMapper.class)).summary(new DashboardQueryReqVO(),true);assertEquals(new java.math.BigDecimal("150.00"),result.getBrowseOrderConversionPercent());assertEquals(Long.valueOf(600),result.getGrossProfit());}
 @Test void siteScope_rejectsProductFilter(){DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("SITE").setSpuId(1L);assertThrows(IllegalArgumentException.class,()->service(mock(TrafficDailyMapper.class),mock(ProductStatisticsMapper.class)).summary(q,false));}
 @Test void productPage_aggregatesSortsAndAppliesBoundedPagination(){ProductStatisticsMapper mapper=mock(ProductStatisticsMapper.class);when(mapper.selectBetween(any(),any())).thenReturn(Arrays.asList(row(1L,40),row(2L,90),row(1L,70)));DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("PRODUCT").setSortField("browseCount").setSortOrder("desc").setPageNo(1).setPageSize(1);List<DashboardProductRespVO> page=service(mock(TrafficDailyMapper.class),mapper).products(q,false);assertEquals(1,page.size());assertEquals(Long.valueOf(1L),page.get(0).getSpuId());assertEquals(Integer.valueOf(110),page.get(0).getBrowseCount());}
 @Test void productPage_rejectsUnknownSortField(){DashboardQueryReqVO q=new DashboardQueryReqVO().setScope("PRODUCT").setSortField("deleted desc");assertThrows(IllegalArgumentException.class,()->service(mock(TrafficDailyMapper.class),mock(ProductStatisticsMapper.class)).products(q,false));}
 private ProductStatisticsDO row(Long spu,int views){return new ProductStatisticsDO().setSpuId(spu).setBrowseCount(views).setTrafficDataStatus(1).setProfitDataQuality(1);}
 private DashboardQueryServiceImpl service(TrafficDailyMapper t,ProductStatisticsMapper p){DashboardQueryServiceImpl s=new DashboardQueryServiceImpl();ReflectionTestUtils.setField(s,"trafficMapper",t);ReflectionTestUtils.setField(s,"productMapper",p);return s;}
}
